monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
    handlers:
        queue:
            type: stream
            path: "%kernel.logs_dir%/queue.log"
            level: info
            channels: [app]
