monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
    handlers:
        main:
            type:  rotating_file
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        queue:
            type: stream
            path: "%kernel.logs_dir%/queue.log"
            level: info
            channels: [app]
